# sft_config.yaml
### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
#FORCE_TORCHRUN: 1
finetuning_type: full
deepspeed: "/home/bjanson/projects/P1/LLaMA-Factory/examples/deepspeed/my_dz_twoGPU.json"  # ds_z2_offload_cpu.json" #Edit if needed
flash_attn: fa2

### dataset
dataset_dir: "/home/bjanson/projects/P1/LLaMA-Factory/data"
dataset: yourdata  # Edit if needed
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 4
template: qwen

### output
output_dir: "/home/bjanson/projects/P1/LLaMA-Factory/logs/qwen25_3b_instruct_h200"      #Edit accordingly
logging_steps: 10
# save_strategy: epoch
save_steps: 1000
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 1      #Edit if needed
gradient_accumulation_steps: 8      #Edit if needed
learning_rate: 1.0e-5               #Edit if needed
num_train_epochs: 7                 #Edit if needed
lr_scheduler_type: cosine
warmup_ratio: 0.0                   #Edit if needed
bf16: true
ddp_timeout: 900

report_to: none # wandb